name: Unit Test

on:
  push:
    branches:
      - main
      - pipeline
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
      - name: Install libs
        run: pip install -r requirement.txt
      - name: Initialize environment
        run: source setupPyPath.sh
      - name: Initialize ssh keys
        uses: 7challenger/init-ssh-js@v1
        with:
          ssh_private_key: ${{ secrets.PRIV_KEY }}
          ssh_public_key: ${{ secrets.PUB_KEY }}
          ssh_known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Authorize key
        run: echo ${{ secrets.PUB_KEY }} > ~/.ssh/authorized_keys
      - name: Unit test execution
        run: python -m unittest -v
